In [20]:
# SORU 1.1

In [4]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz = list(set(notlar))
print("Benzersiz:", benzersiz)


Benzersiz: [100, 92, 85, 76]


In [22]:
# SORU 1.2

In [6]:
# En yüksek ve en düşük
print("En yüksek:", max(notlar))
print("En düşük:", min(notlar))

En yüksek: 100
En düşük: 76


In [24]:
# SORU 1.3

In [8]:
# Küçükten büyüğe sıralama
sirali = sorted(notlar)
print("Sıralı:", sirali)

Sıralı: [76, 76, 85, 85, 92, 92, 92, 100]


In [26]:
# SORU 2

In [10]:
def armstrong_mu(sayi):
    basamaklar = [int(d) for d in str(sayi)]
    toplam = sum([b**3 for b in basamaklar])
    return toplam == sayi

print(153, armstrong_mu(153))
print(123, armstrong_mu(123))


153 True
123 False


In [28]:
# SORU 3

In [12]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Ortak:", A & B)
print("Sadece A’da:", A - B)
print("Birleşim (alfabetik):", sorted(A | B))

Ortak: {'SQL', 'Python'}
Sadece A’da: {'Java', 'R'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [30]:
# SORU 4

In [14]:
import random, statistics

sayilar = [random.randint(1,100) for _ in range(10)]
print("Sayılar:", sayilar)
print("Ortalama:", statistics.mean(sayilar))
print("Standart Sapma:", statistics.stdev(sayilar))

Sayılar: [45, 24, 16, 53, 7, 19, 15, 44, 93, 89]
Ortalama: 40.5
Standart Sapma: 30.55868670825586


In [ ]:
# SORU 5

In [36]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    en_uzun = max(kelimeler, key=len)
    en_sik = max(set(kelimeler), key=kelimeler.count)
    return len(kelimeler), en_uzun, en_sik

print(kelime_sayaci("veri bilim veri python analiz veri"))

(6, 'python', 'veri')


In [ ]:
# SORU 6

In [38]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x%2==0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan kareler:", sirali)


Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan kareler: [576, 324, 256, 144]


In [ ]:
# SORU 7

In [42]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "jupyter"]
sirali = sorted(kelimeler, key=lambda x: len(x))
print(sirali)


['veri', 'bilim', 'analiz', 'jupyter', 'yapayzeka']


In [44]:
# SORU 8

In [46]:
def rakam_toplami(s):
    rakamlar = [int(ch) for ch in s if ch.isdigit()]
    return sum(rakamlar)

print(rakam_toplami("abc12def3"))


6


In [48]:
# SORU 9 

In [50]:
import numpy as np

dizi = np.random.randint(0,51,10)
print("Dizi:", dizi)
print("Ortalama:", dizi.mean())
print("Std Sapma:", dizi.std())
print("En büyük:", dizi.max())


Dizi: [ 8 37 49 24 41 18  4 31 39 15]
Ortalama: 26.6
Std Sapma: 14.361058456812994
En büyük: 49


In [52]:
# SORU 10  

In [54]:
matris = np.random.rand(5,5)
print("Matris:\n", matris)
print("Sütun ortalamaları:", matris.mean(axis=0))

binary = (matris > 0.5).astype(int)
print("Binary matris:\n", binary)


Matris:
 [[0.05939244 0.94855045 0.92994602 0.01757883 0.15981079]
 [0.14593001 0.11562013 0.80414151 0.91899189 0.97840457]
 [0.83530269 0.78135623 0.07079842 0.58173825 0.50307688]
 [0.97731332 0.01172775 0.81292824 0.18122773 0.04833954]
 [0.90622795 0.04968277 0.51059119 0.68272483 0.411374  ]]
Sütun ortalamaları: [0.58483328 0.38138747 0.62568108 0.47645231 0.42020116]
Binary matris:
 [[0 1 1 0 0]
 [0 0 1 1 1]
 [1 1 0 1 1]
 [1 0 1 0 0]
 [1 0 1 1 0]]
